# Generated by Django 6.0.2 on 2026-03-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
