# Generated by Django 6.0.2 on 2026-03-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_inspectionmeeting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
        migrations.AddField(
            model_name="booking",
            name="preferred_date",
            field=models.DateField(default="2026-03-25"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="preferred_time",
            field=models.TimeField(default="09:00:00"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]