# Generated by Django 6.0.2 on 2026-03-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_email_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archived_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
