# Generated by Django 6.0.2 on 2026-03-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_archived_by_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='archived_by_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
