# Generated by Django 6.0.2 on 2026-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_property_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('inspection_request', 'Inspection Request'), ('inspection_confirmed', 'Inspection Confirmed'), ('property_booked', 'Property Booked'), ('property_submitted', 'Property Submitted'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected')], max_length=50),
        ),
    ]
