# Generated by Django 6.0.2 on 2026-03-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_remove_notification_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('inspection_request', 'Inspection Request'), ('inspection_confirmed', 'Inspection Confirmed'), ('property_booked', 'Property Booked'), ('property_submitted', 'Property Submitted'), ('property_approved', 'Property Approved'), ('property_rejected', 'Property Rejected'), ('property_flagged', 'Property Flagged'), ('property_hidden', 'Property Hidden')], max_length=50),
        ),
    ]
