# Generated by Django 6.0.2 on 2026-03-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('ahafo', 'Ahafo'), ('ashanti', 'Ashanti'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('central', 'Central'), ('eastern', 'Eastern'), ('greater_accra', 'Greater Accra'), ('north_east', 'North East'), ('northern', 'Northern'), ('oti', 'Oti'), ('savannah', 'Savannah'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('volta', 'Volta'), ('western', 'Western'), ('western_north', 'Western North')], max_length=50),
        ),
    ]
