# Generated by Django 6.0.2 on 2026-03-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_location_remove_property_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
