# Generated by Django 6.0.2 on 2026-03-20 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_owner_externallandlord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('external_landlord__isnull', True)), models.Q(('owner__isnull', True), ('external_landlord__isnull', False)), _connector='OR'), name='property_exactly_one_owner_source'),
        ),
    ]
