# Generated by Django 6.0.2 on 2026-03-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_approval_status_property_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
