# Generated by Django 6.0.2 on 2026-03-24 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='security_flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_flag_type',
            field=models.CharField(blank=True, choices=[('duplicate_property', 'Duplicate Property')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='security_under_review',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PropertyDuplicateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_reason', models.TextField()),
                ('match_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_by_duplicates', to='properties.property')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('property', 'matched_property'), name='unique_property_duplicate_match'), models.CheckConstraint(condition=models.Q(('property', models.F('matched_property')), _negated=True), name='property_duplicate_match_not_self')],
            },
        ),
    ]
