# Generated by Django 6.0.2 on 2026-03-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_security_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
