# Generated by Django 6.0.2 on 2026-03-25 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyimage_image_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='propertyduplicatematch',
            name='property_duplicate_match_not_self',
        ),
        migrations.AlterField(
            model_name='externallandlord',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='landlord_documents/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='external_landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.externallandlord'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='propertyduplicatematch',
            constraint=models.CheckConstraint(condition=models.Q(('property_id', models.F('matched_property_id')), _negated=True), name='property_duplicate_match_not_self'),
        ),
    ]
