# Generated by Django 6.0.2 on 2026-03-26 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_remove_propertyduplicatematch_property_duplicate_match_not_self_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('gender_restriction', models.CharField(choices=[('male', 'Male only'), ('female', 'Female only'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('occupied_spaces', models.PositiveIntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('occupied_spaces__lte', models.F('max_capacity'))), name='room_occupied_lte_max_capacity'), models.CheckConstraint(condition=models.Q(('max_capacity__gte', 1), ('max_capacity__lte', 6)), name='room_max_capacity_between_1_and_6')],
                'unique_together': {('property', 'room_number')},
            },
        ),
    ]
