# Generated by Django 6.0.2 on 2026-03-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_property_created_by_admin_property_support_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='report_flag_reason_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='property',
            name='report_flag_status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('hidden', 'Hidden'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='report_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='report_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='reported_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
