# Generated by Django 6.0.2 on 2026-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_report_flag_reason_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='report_flag_status',
            field=models.CharField(choices=[('active', 'Active'), ('flagged', 'Flagged'), ('hidden', 'Hidden'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved')], default='active', max_length=20),
        ),
    ]
