# Generated by Django 6.0.2 on 2026-06-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_property_report_flag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.CharField(choices=[('ahafo', 'Ahafo'), ('ashanti', 'Ashanti'), ('bono', 'Bono'), ('bono_east', 'Bono East'), ('central', 'Central'), ('eastern', 'Eastern'), ('greater_accra', 'Greater Accra'), ('north_east', 'North East'), ('northern', 'Northern'), ('oti', 'Oti'), ('savannah', 'Savannah'), ('upper_east', 'Upper East'), ('upper_west', 'Upper West'), ('volta', 'Volta'), ('western', 'Western'), ('western_north', 'Western North')], max_length=50),
        ),
    ]
