# Generated by Django 6.0.2 on 2026-07-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_alter_property_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allowed_rental_months',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
