# Generated by Django 6.0.2 on 2026-07-16 07:47

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_allowed_rental_months'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='reserved_spaces',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('property', 'room_number'), name='unique_property_room_number'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_spaces__lte', models.F('max_capacity'))), name='room_reserved_lte_max_capacity'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(condition=models.Q(('occupied_spaces__lte', django.db.models.expressions.CombinedExpression(models.F('max_capacity'), '-', models.F('reserved_spaces')))), name='room_used_spaces_lte_max_capacity'),
        ),
    ]
