# Generated by Django 6.0.2 on 2026-08-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment_listing_type',
            field=models.CharField(blank=True, choices=[('single', 'Single Apartment'), ('multi_unit', 'Multiple Apartment Units')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('hostel', 'Hostel'), ('house_rent', 'House for Rent'), ('apartment', 'Apartment')], max_length=50),
        ),
        migrations.CreateModel(
            name='ApartmentUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('floor', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_furnished', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], db_index=True, default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_units', to='properties.property')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('property', 'unit_number'), name='unique_property_apartment_unit')],
            },
        ),
    ]
