# Generated by Django 6.0.2 on 2026-06-19 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Mobile money number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ghana phone number. Example: 0541234567', regex='^0\\d{9}$')])),
                ('provider', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('telecel', 'Telecel Cash'), ('airteltigo', 'AirtelTigo Money'), ('bank', 'Bank Account')], max_length=20)),
                ('paystack_subaccount_code', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_four_digits', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Payment Account',
                'verbose_name_plural': 'Owner Payment Accounts',
            },
        ),
    ]
