# Generated by Django 6.0.2 on 2026-06-19 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookingidempotencykey'),
        ('payments', '0001_initial'),
        ('properties', '0017_alter_property_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('rent_and_deposit', 'Rent and Deposit')], default='rent_and_deposit', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=120, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=120)),
                ('paystack_authorization_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('paystack_response', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_payments', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='payments_pa_tenant__3ffcb1_idx'), models.Index(fields=['landlord', 'status'], name='payments_pa_landlor_ebd781_idx'), models.Index(fields=['property', 'status'], name='payments_pa_propert_a7fabf_idx')],
            },
        ),
    ]
