# Generated by Django 6.0.2 on 2026-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='duration_months',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Pay through UrbanHavens'), ('direct', 'Pay Owner Directly')], default='paystack', max_length=20),
        ),
    ]
