# Generated by Django 6.0.2 on 2026-07-15 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_booking_status'),
        ('payments', '0003_payment_duration_months_payment_payment_method'),
        ('properties', '0018_property_allowed_rental_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount expected to be settled to the property owner.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Transaction fee charged by Paystack.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='UrbanHavens commission amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_account',
            field=models.CharField(blank=True, default='', help_text='Masked settlement account or subaccount reference.', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='settlement_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Awaiting Paystack Settlement'), ('processing', 'Settlement Processing'), ('paid', 'Paid to Owner'), ('failed', 'Settlement Failed')], db_index=True, default='not_applicable', max_length=30),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['landlord', 'settlement_status'], name='payments_pa_landlor_88f83f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'settlement_status'], name='payments_pa_payment_bc8b44_idx'),
        ),
    ]
