# Generated by Django 6.0.2 on 2026-07-16 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('payments', '0004_payment_owner_net_amount_payment_paystack_fee_and_more'),
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.room'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['room', 'status'], name='payments_pa_room_id_df743c_idx'),
        ),
    ]
