# Generated by Django 6.0.2 on 2026-07-16 09:55

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('payments', '0005_payment_room_payment_payments_pa_room_id_df743c_idx'),
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_completion_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('part', 'Part Payment'), ('full', 'Full Payment'), ('overpaid', 'Overpaid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ownerpaymentaccount',
            name='phone_number',
            field=models.CharField(help_text='Mobile money number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ghana phone number. Example: 0541234567', regex='^0\\\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'payment_completion_status'], name='payments_pa_status_14dc02_idx'),
        ),
    ]
