# Generated by Django 6.0.2 on 2026-07-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('leases', '0006_leaserenewalrequest'),
        ('payments', '0006_payment_amount_received_payment_expected_amount_and_more'),
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='renewal_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal_payment', to='leases.leaserenewalrequest'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('deposit', 'Deposit'), ('rent_and_deposit', 'Rent and Deposit'), ('renewal', 'Lease Renewal')], default='rent_and_deposit', max_length=30),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['renewal_request', 'status'], name='payments_pa_renewal_4d6958_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('renewal_request__isnull', True)), models.Q(('booking__isnull', True), ('renewal_request__isnull', False)), _connector='OR'), name='payment_exactly_one_source'),
        ),
    ]
