# Generated by Django 6.0.2 on 2026-07-21 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_renewal_request_alter_payment_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerpaymentaccount',
            name='phone_number',
            field=models.CharField(help_text='Mobile money number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ghana phone number. Example: 0541234567', regex='^0\\d{9}$')]),
        ),
    ]
