# Generated by Django 6.0.2 on 2026-08-19 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('leases', '0008_alter_leaserenewalrequest_options_and_more'),
        ('payments', '0008_alter_ownerpaymentaccount_phone_number'),
        ('properties', '0020_property_apartment_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='apartment_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.apartmentunit'),
        ),
        migrations.AlterField(
            model_name='ownerpaymentaccount',
            name='phone_number',
            field=models.CharField(help_text='Mobile money number', max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid Ghana phone number. Example: 0541254645', regex='^0\\d{9}$')]),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['apartment_unit', 'status'], name='payments_pa_apartme_089ffd_idx'),
        ),
    ]
