# Generated by Django 6.0.2 on 2026-03-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantlease',
            name='room_number',
            field=models.CharField(blank=True, help_text="Room number or label for hostel properties (e.g. '101', 'A4')", max_length=20, null=True),
        ),
    ]
