# Generated by Django 6.0.2 on 2026-03-26 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0003_alter_tenantlease_room_number'),
        ('properties', '0013_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantlease',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tenantlease',
            name='room_number',
        ),
        migrations.AddField(
            model_name='tenantlease',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='properties.room'),
        ),
    ]
