# Generated by Django 6.0.2 on 2026-07-16 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('leases', '0004_alter_tenantlease_options_and_more'),
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantlease',
            name='agreement_generated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tenantlease',
            name='agreement_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantlease',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tenantlease',
            index=models.Index(fields=['tenant', 'status'], name='leases_tena_tenant__15f41d_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlease',
            index=models.Index(fields=['landlord', 'status'], name='leases_tena_landlor_e7a509_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlease',
            index=models.Index(fields=['property', 'status'], name='leases_tena_propert_32d7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlease',
            index=models.Index(fields=['room', 'status'], name='leases_tena_room_id_317fa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenantlease',
            constraint=models.UniqueConstraint(condition=models.Q(('booking__isnull', False)), fields=('booking',), name='unique_lease_per_booking'),
        ),
    ]
