# Generated by Django 6.0.2 on 2026-07-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_tenantlease_agreement_generated_at_and_more'),
        ('payments', '0006_payment_amount_received_payment_expected_amount_and_more'),
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_duration_months', models.PositiveIntegerField()),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewal_requests', to='leases.tenantlease')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landlord_renewal_requests', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_renewal_request', to='payments.payment')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_renewal_requests', to='properties.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_renewal_requests', to='properties.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_renewal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
