# Generated by Django 6.0.2 on 2026-07-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0006_leaserenewalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('expiry_30_day_reminder', '30-Day Expiry Reminder'), ('expiry_14_day_reminder', '14-Day Expiry Reminder'), ('expiry_7_day_reminder', '7-Day Expiry Reminder'), ('lease_expired', 'Lease Expired'), ('expiry_blocked_by_renewal', 'Expiry Blocked by Renewal'), ('renewal_payment_cancelled', 'Renewal Payment Cancelled'), ('renewal_completed', 'Renewal Completed')], max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='leases.tenantlease')),
                ('renewal_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifecycle_events', to='leases.leaserenewalrequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='leases_leas_event_t_cda5f1_idx'), models.Index(fields=['lease', 'created_at'], name='leases_leas_lease_i_f46eae_idx')],
                'constraints': [models.UniqueConstraint(fields=('lease', 'event_type'), name='unique_lease_lifecycle_event_type')],
            },
        ),
    ]
