# Generated by Django 6.0.2 on 2026-07-17 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0007_leaselifecycleevent'),
        ('payments', '0007_payment_renewal_request_alter_payment_booking_and_more'),
        ('properties', '0019_alter_room_unique_together_room_reserved_spaces_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaserenewalrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='leaserenewalrequest',
            index=models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9a41a7_idx'),
        ),
        migrations.AddIndex(
            model_name='leaserenewalrequest',
            index=models.Index(fields=['landlord', 'status'], name='leases_leas_landlor_aa276b_idx'),
        ),
        migrations.AddIndex(
            model_name='leaserenewalrequest',
            index=models.Index(fields=['current_lease', 'status'], name='leases_leas_current_d72a62_idx'),
        ),
        migrations.AddIndex(
            model_name='leaserenewalrequest',
            index=models.Index(fields=['property', 'status'], name='leases_leas_propert_bd83e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaserenewalrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'payment_pending', 'payment_completed'])), fields=('current_lease',), name='unique_open_renewal_per_lease'),
        ),
    ]
