# Generated by Django 6.0.2 on 2026-08-19 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_status'),
        ('leases', '0008_alter_leaserenewalrequest_options_and_more'),
        ('payments', '0009_payment_apartment_unit_and_more'),
        ('properties', '0020_property_apartment_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserenewalrequest',
            name='apartment_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_renewal_requests', to='properties.apartmentunit'),
        ),
        migrations.AddField(
            model_name='tenantlease',
            name='apartment_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='properties.apartmentunit'),
        ),
        migrations.AddIndex(
            model_name='leaserenewalrequest',
            index=models.Index(fields=['apartment_unit', 'status'], name='leases_leas_apartme_de3ece_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantlease',
            index=models.Index(fields=['apartment_unit', 'status'], name='leases_tena_apartme_07bf25_idx'),
        ),
    ]
