# Generated by Django 6.0.2 on 2026-03-30 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sms', 'SMS'), ('api_error', 'API Error'), ('booking', 'Booking'), ('notification', 'Notification'), ('meeting', 'Meeting')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('info', 'Info')], max_length=10)),
                ('message', models.TextField()),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.IntegerField(blank=True, null=True)),
                ('meeting_id', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
