# Generated by Django 6.0.2 on 2026-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='property_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='category',
            field=models.CharField(choices=[('sms', 'SMS'), ('api_error', 'API Error'), ('booking', 'Booking'), ('notification', 'Notification'), ('meeting', 'Meeting'), ('property', 'Property')], max_length=20),
        ),
    ]
