# Generated by Django 6.0.2 on 2026-03-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('admin', 'Admin')], default='tenant', max_length=20),
        ),
    ]
